import Head from 'next/head'
import {Hero} from "../components/sections/hero";
import {About} from "../components/sections/about";
import Project from "../components/sections/project";
import {getAllProjects} from "../utils/project-util";
import {Contact} from "../components/sections/contact";

export default function Home(props:any) {

    const {projects} = props;

  return (
    <>
      <Head>
        <title>Xinyue Chen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-28 px-6 md:px-20 lg:px-52 grid grid-cols-1 lg:max-w-screen-2xl lg:mx-auto ">
          <Hero />
          <About />
          <Project projects={projects}/>
          <Contact />
      </main>
    </>
  )
}

export async function getStaticProps() {

    const projects = getAllProjects();

    return {
        props: {
            projects: projects
        },
        revalidate: 10
    }
}
